name: Deploy # 自动部署的名称
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Build project
        run: yarn && yarn build


      - name: upload .nuxt
        uses: hengkx/ssh-deploy@v1.0.1
        with: # 以下为参数
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          SOURCE: '.nuxt'
          TARGET: /site/temp/.nuxt
     
      - name: upload static
        uses: hengkx/ssh-deploy@v1.0.1
        with: # 以下为参数
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          SOURCE: static
          TARGET: /site/temp/static


      - name: upload nuxt.config.js & package.json
        uses: appleboy/scp-action@master
        with: # 以下为参数
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          source: 'nuxt.config.js,package.json'
          target: /site/temp

      - name: Sever Options
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: | # 清除缓存
            cd /site/nuxt_hardware
            rm -rf .nuxt nuxt.config.js package.json
            mv /site/temp/* /site/nuxt_hardware
            yarn
            pm2 start npm -- start
