# 当代码推动到 dev 分支时，执行当前工作流程
# 更多配置信息: https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy serverless

on: #监听的事件和分支配置
  push:
    branches:
      - master 

jobs:
  test: #配置单元测试
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: unit test
        run: '' 
  deploy:
    name: deploy serverless
    steps:
      - name: clone local repository
      - name: build
        run: npm run build
      - name: deploy serverless
        run: npm run deploy
        env: # 环境变量
          STAGE: master #您的部署环境
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: AKIDaxFMI22ejslX1GQxFLOCD5k8F6g1NTaU #您的腾讯云账号 sercret ID
          TENCENT_SECRET_KEY: tmRu8BbFeneZEqX0nHYcqsfgRyFEyK8i #您的腾讯云账号 sercret key
